# Generated by Django 3.0.2 on 2020-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=17, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=35, verbose_name='이름(활동명)')),
                ('phone', models.IntegerField(null=True, unique=True, verbose_name='핸드폰번호')),
                ('sns', models.CharField(max_length=35, unique=True, verbose_name='SNS아이디')),
                ('level', models.CharField(choices=[('2', 'Lv2_일반사용자'), ('1', 'Lv1_인증사용자'), ('0', 'Lv0_관리자')], default=2, max_length=24, verbose_name='등급')),
                ('location', models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('세종', '세종'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], max_length=24, verbose_name='거주지')),
                ('genre', models.CharField(choices=[('노래', '노래'), ('악기', '악기'), ('영화', '영화')], max_length=24, verbose_name='분야')),
                ('position', models.CharField(choices=[('작사', '작사'), ('작곡', '작곡'), ('보컬', '보컬'), ('기타', '기타'), ('키보드', '키보드'), ('드럼', '드럼'), ('연기', '연기'), ('촬영', '촬영')], max_length=24, verbose_name='세부분야')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='프로필사진')),
                ('registered_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': '회원목록',
            },
        ),
    ]
