# Generated by Django 3.0.2 on 2020-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('노래', '노래'), ('악기', '악기'), ('영화', '영화')], max_length=24, null=True, verbose_name='분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('세종', '세종'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], max_length=24, null=True, verbose_name='거주지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=35, null=True, verbose_name='이름(활동명)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('작사', '작사'), ('작곡', '작곡'), ('보컬', '보컬'), ('기타', '기타'), ('키보드', '키보드'), ('드럼', '드럼'), ('연기', '연기'), ('촬영', '촬영')], max_length=24, null=True, verbose_name='세부분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sns',
            field=models.CharField(max_length=35, null=True, unique=True, verbose_name='SNS아이디'),
        ),
    ]
